### ISSUE TITLE
How to define an alias

### ISSUE THREAD

**Issue by vityou** [willghatch/racket-rash#11]
For example if I wanted to make ls run `ls --color=auto`, or make `la` run `ls -a`, how would I do that?  Also, how do you define or edit environment variables like `PATH`?  Thanks for any help.

**Comment by willghatch** [comment]
Thanks for raising this issue.  I need to document that.  But for a quick answer, yes you can do that, and your problem is probably that my demo file has all the alias arguments in quotes or strings.  Try this:

```
(define-simple-pipeline-alias ls 'ls --color=auto)
(define-simple-pipeline-alias la ls -a)
```

If a command name is quoted or in a string it will NOT be expanded as an alias.  But since the second one doesn't quote it it will look it up.

There is also a more powerful `define-pipeline-alias` which basically lets you define an alias to be whatever syntax transformer you want if you want to do something more complicated.

**Comment by vityou** [comment]
Ah, that makes sense, not sure why I didn't try that.

**Comment by willghatch** [comment]
Actually, I'm going to leave this open until I write the actual documentation.
