### ISSUE TITLE
What is the language of the rashrc file

### ISSUE THREAD

**Issue by vityou** [willghatch/racket-rash#12]
I was playing around with the `.config/rash/rashrc` file, and noticed that it wasn't normal racket syntax.  When I added `cd /`, that action was performed, but when I added `ls /`, I got an error:
```
error in rc file /home/vityou/.config/rash/rashrc: .racket/6.12/pkgs/shell-pipeline/private/pipeline-operator-transform.rkt:14:60: erroring-default-pipeline-starter: No explicit pipeline starter given in a context with no default set.
  in: (default-pipeline-starter-macro ls /)
  context...:
   dots-loop
   /home/vityou/.racket/6.12/pkgs/rash/repl.rkt:134:2: for-loop
   /home/vityou/.racket/6.12/pkgs/rash/repl.rkt:116:0: main
   /home/vityou/.racket/6.12/pkgs/rash/repl.rkt: [running body]
```
I'm not really sure what exactly it means, but allowing `cd /` and not other things doesn't seem like intended behavior.  I think it has something to do with `cd` being part of the shell and `ls` being external.

**Comment by willghatch** [comment]
That's a bug.  Thanks.

The rashrc should be the same language that you type into the repl.  But I had left a configuration option off of the function that evaluated the rc file.  I've now merged the two bits of code into a function to ensure the language is the same.  It's fixed in 9e1a9e848e1f8cc87f4e7ecde10f92d95bfcd957.

Thanks for using Rash, and keep posting issues.  If you have any other questions, comments, or suggestions I'm happy to hear them.
