### ISSUE TITLE
Line macro not being applied to included file

### ISSUE THREAD

**Issue by vityou** [willghatch/racket-rash#13]
Sorry if this isn't the right place to ask.  I created a line macro for aliases like this:
```
(define-line-macro alias
  (syntax-parser
    [(_ i (~datum =) value ...) #'(define-simple-pipeline-alias i value ...)]))
```
I decided to separate my aliases into a file called `aliases.rash`, and I defined the line macro in the `rashrc` file, and used `include` to run the alias file.  However, I get an error saying bad syntax in alias.  This didn't happen when I defined the macro in the `aliases.rash` file.  I suspect it may have something to do with syntax, or I'm just using `include` wrong.

**Comment by vityou** [comment]
Here are both files:

`rashrc`:
```
(require rash/demo/demo-rc)
(require racket/include)


; allows defining aliases in the form of
; alias x = y
(define-line-macro alias
  (syntax-parser
    [(_ i (~datum =) value ...) #'(define-simple-pipeline-alias i value ...)]
    [(_ i value ...) #'(define-simple-pipeline-alias i value ...)]))

; alias file
(include (file "aliases.rash"))
```

`aliases.rash`:
```
; written in racket rash language

; ls aliases
alias ls = 'ls_extended
alias la = ls -a
alias ll = ls -la
alias l = ls -l
```

**Comment by willghatch** [comment]
Hmm, I've never actually used `include`.  But I bet the problem is that `include` reads the given file with the default reader, which is different from the Rash reader.

But I would not recommend using `include` anyway.  Rather, use `require` instead.  In fact, the `rashrc` should optimally only include some basic things that change the live namespace.  Any definitions are best put in a normal module and `require`d, either in a `rashrc` or required and re-exported in a `rashrc.rkt` module.

**Comment by willghatch** [comment]
You could put the aliases as written in an `aliases.rkt` file in `#lang rash`, add `(provide (all-defined-out))`, and then require it.

**Comment by vityou** [comment]
I believe it has something to do with `ls` being a read program, because when I make an alias called `asdf123` set to `ls_extended`, it behaves normally.  I'm not sure why this happens, because if I type `alias ls = 'ls_extended` into the repl, it works normally.

**Comment by vityou** [comment]
Ok, sorry for the wall of text but I think I figured it out.  The `rashrc` file requiring the `demo-rc` file was somehow overriding the `ls` alias from my personal file, I couldn't find exactly where.  So I guess your mentioned `alias.rkt` and `rashrc.rkt` using `require` and `provide` does work.

**Comment by willghatch** [comment]
Oh, yeah, I didn't think about that.  The demo rc file includes an `ls` definition, as well as a few other things.   Some of those things should probably move into some default thing (or better implementations of them should), and otherwise I should make the demo rc be exactly that -- just a demo that you would look at for inspiration to write your own rc file if you want any customizations.
