### ISSUE TITLE
rash logo

### ISSUE THREAD

**Issue by vityou** [willghatch/racket-rash#21]
Well, instead of looking at the code, I decided to try and make a logo for rash.  Tell me if you wan't me to change anything or if you don't want to use it that's fine.

<img src="https://rawgit.com/vityou/test/master/rash-icon.svg">

**Comment by willghatch** [comment]
This looks great!

A few comments:

* Is there an explicit license for the Racket logo somewhere?  I would assume it's GPLv3 or something compatible, since it's Racket's own logo.  Likely Apache or MIT since that's what the core Racket devs are switching it to at some point.
* I've kind of thought it might be nice to have a phosphorescent green on black logo for rash -- in the spirit of old-timey terminals.  That may or may not actually look good.  Would you try making a version that is like that?  If it doesn't look good, let's use this one.
* If there is a logo, I'm going to get stickers printed to put on my laptop and such.  But I hate it when those stickers have no words or URL or something, because then you can't really look them up.  So I would also want a version with words.  Do you think they would go better just below the logo or inside the logo -- eg. “rash” written inside along with the cursor?  That might ruin it.  At any rate I have been planning to register some appropriate domain name for Rash, and I'll do that soon.  Then maybe the domain name can be the text that goes... probably underneath the logo.

**Comment by willghatch** [comment]
(I didn't mean to close it -- I just hit the wrong comment button.)

**Comment by willghatch** [comment]
And now I have rash-lang.org, though I probably won't put anything interesting there for a while.

**Comment by vityou** [comment]
Sounds good.  I asked in the mailing list what would be the best way to use the logo and give credit, I attempted to give credit in a comment in the svg, but I'd assume that's not enough.

I'll see if I can make a nice looking green on black one.

For the words, I'd say they would go better on the bottom, but I'll have to see what font would be nicest.  I did try doing this, but it looked kinda awkward because rash is only 4 letters, so I may have to shorten the width of the logo with words.

I could also make a gif version with a blinking cursor for websites, but that may be over the top.

**Comment by vityou** [comment]
The text aspect of this could be problematic.  If a website doesn't support the font, it renders pretty ugly, if it's an svg.

I found a way to make the racket logo work with the glow effect.  So this on may look nicer.

<img src="https://rawgit.com/vityou/test/master/rash-icon-green-with-racket-symbol.svg">

**Comment by vityou** [comment]
Here is a sticker version as a png so the font is correct:

<img src="https://github.com/vityou/test/raw/master/rect857.png">

**Comment by willghatch** [comment]
Ooo, I really like it.  But let's have the sticker version say “rash-lang.org” instead of “rash”.  Searching for “rash” without something more specific will get... unhappy biological results rather than shell language results.  A downside of the name.

**Comment by vityou** [comment]
Oh yeah, probably not a good idea haha.

<img src="https://rawgit.com/vityou/test/master/rash-icon-green-with-racket-symbol-text-fixed.svg">

**Comment by vityou** [comment]
All the logos are svg, so if you wan't to tweak the glowing effect or change the cursor style later you can open them in inkscape or something.  Also I'd recommend downloading them from the repo I uploaded them to here: https://github.com/vityou/test because I've changed some things like making the text an svg path, and the ones on this issue are old cached versions.

**Comment by vityou** [comment]
It looks like the racket logo is ok to use.  Matthew Butterick, who created it said that it falls under the LGPL license with the rest of racket.  I don't have extensive knowledge of licenses, but I think there just has to be a copy of the svg source available.

**Comment by willghatch** [comment]
I've merged the commit that contains the logo, so I'm closing this.
