### ISSUE TITLE
commenting code

### ISSUE THREAD

**Issue by vityou** [willghatch/racket-rash#22]
Are you okay with comments above functions in the code that describe what they do for more complex functions?  I was reading over the code and was wondering if I could write some in to understand how the code works better.  But some people find that it clutters the code so I wanted to make sure.

**Comment by vityou** [comment]
Also, would you prefer if tests were written in separate files, or in the test submodule in each file?

**Comment by willghatch** [comment]
I have a mix of both.  That could potentially be improved, but I don't have strong feelings right now.  A `module+` submodule lets you test private functions that you don't export, so I always use `module+` for that.  But some higher-level things that test things from multiple files I've put into their own test file.  I'm happy for you to add tests anywhere.  I didn't test much as I was writing things because my design kept changing and I didn't want to have to keep tests in sync.  But now things have solidified a lot more and I've been trying to add more tests as I implement things.  All around, though, I would say my software engineering discipline is not at a high level in this regard.

One thing I would ask, though, is not to put tests that use subprocesses or the file system in the test submodules.  The automated testing that the Racket build server does uses a sandbox that disallows such things, so those tests will always be reported by the package server as failing.  I have such tests in a `main` submodule somewhere, I think, but it may be best to put them in a `non-sandboxed-test` submodule that the test server won't pick up, but that we hit with a testing script.  Probably we would hook that up to Travis.

Speaking of Travis, I have never actually used Travis, and I only have a moment free and with internet access right now.  So I'm going to look at your PR and get Travis set up later.  Likely tonight, but maybe not until tomorrow or Friday.

**Comment by willghatch** [comment]
Oh, and to answer the original question -- yes, you can comment things.  I've been meaning to comment complicated things more, and if you start commenting the ones that you find confusing that will be even better.  If you have trouble understanding one, feel free to put a TODO comment for me to write some commentary explaining things.  These comments may be permanent or may be a hint that things should be simplified by refactoring, better naming, etc.  But I imagine the more complicated macro bits especially will warrant some commentary permanently.
