### ISSUE TITLE
error running any command in rash on racket 6.12

### ISSUE THREAD

**Issue by cinterloper** [willghatch/racket-rash#25]
I have installed racket 6.12  from the PPA on ubuntu 18.04.
I have also installed rash from raco
When I attempt to use rash, I get the following issue:

```

$ raco pkg show rash
Installation-wide:
 [none]
User-specific for installation "6.12":
 Package  Checksum                Source
 rash     8c75faf666c6376d965...  catalog...it?path=rash
$ racket --version
Welcome to Racket v6.12.


$ dpkg -l | grep racket
ii  racket                                6.12+ppa1-1~bionic2                  amd64        extensible programming language in the Scheme family
ii  racket-common                         6.12+ppa1-1~bionic2                  all          extensible programming language in the Scheme family (shared files)
ii  racket-doc                            6.12+ppa1-1~bionic2                  all          extensible programming language in the Scheme family (documentation)
```
```
$ racket -I rash
Welcome to Racket v6.12.
> ls
; readline-input:1:0: #%top-interaction: unbound identifier;
;  also, no #%app syntax transformer is bound
;   at: #%top-interaction
;   in: (#%top-interaction . ls)
; [,bt for context]
>
```

I saw some similar issues, and they seemed to say update the readline-lib package. I am however already on 6.12 and when I try to update readline-lib, I have the following issues:

```
$ raco pkg update --clone readline-lib
Inferred package name from given `--clone' path
  package: readline-lib
  given path: readline-lib
Inferred package scope: installation
open-output-file: cannot open output file
  path: /usr/share/racket/pkgs/.LOCKpkgs.rktd
  system error: Permission denied; errno=13
  context...:
   /usr/share/racket/collects/racket/private/kw-file.rkt:116:2: call-with-output-file*70
   /usr/share/racket/collects/racket/file.rkt:334:2: loop
   /usr/share/racket/collects/pkg/main.rkt:305:16
   (submod /usr/share/racket/collects/pkg/main.rkt main): [running body]
   /usr/share/racket/collects/pkg/raco.rkt: [traversing imports]
   /usr/share/racket/collects/raco/raco.rkt: [running body]
   /usr/share/racket/collects/raco/main.rkt: [running body]
```
```
#  raco pkg update --clone readline-
Inferred package name from given `--clone' path
  package: readline-lib
  given path: readline-lib
Inferred package scope: installation
raco pkg update: package is not currently installed from a repository
  package: readline-lib
  current installation: (catalog readline-lib)
```
I am a racket beginner, so please forgive me if I am missing something obvious.

**Comment by vityou** [comment]
I'm no racket/rash expert myself, but to my knowledge, the error you get with `racket -I rash` means that the rash language isn't setup to be run in a repl. in a language like racket, `#%top-interaction` would be wrapped around what you type into the repl.

But, there is a reason `racket -I rash` doesn't work.  This is because rash comes with its own repl that is better than racket's normal one.  You can invoke this by running `racket -l rash/repl`, which is equivalent to typing (`(require rash/repl)`) if you were already inside the racket repl.

**Comment by cinterloper** [comment]
Ah, thanks @vityou , that worked.

**Comment by willghatch** [comment]
I would say that `rash-repl` is not really *better* than Racket's shell, just different.  I don't think there is a way (I hope to be proven wrong) to set the reader for the default Racket repl, only the bindings, so I had to make my own repl module.  But I do hope to make a better repl in the future.  And it is not like adding `(require rash/repl)` to a module or in the repl, but it is more like having `#lang rash` at the top of a file, except that it is a repl instead of a module.

**Comment by vityou** [comment]
If I open a racket repl and do a `(require rash/repl)`, the rash repl pops up with the correct prompt and everything.  Doesn't is pretty much just run the `(main)` function located in `rash/repl`?
