### ISSUE TITLE
`pre-readline-input-port: unbound identifier in module` in `repl.rkt`

### ISSUE THREAD

**Issue by Ninlives** [willghatch/racket-rash#3]
And I didn't find this definition in the redline lib. May be removed  in the new version?

**Comment by willghatch** [comment]
The opposite, rather.  It is in the newest version in git.  I think it will be in the release that is happening soon.  But you can also do `raco pkg update --clone readline-lib` to get the latest version.

I added the pre-readline-input-port to be able to use Racket's readline FFI module for the rash repl.  Otherwise every pipeline that normally doesn't read stdin (eg. `ls`) would eat some of the input due to the impedance mismatch between racket ports and OS file descriptors.  I had been using `rlwrap` to get some line editing before, but this gives full readline editing inside the repl, including completion.

**Comment by willghatch** [comment]
Oh, be sure to do `raco pkg update --clone readline-lib` in some directory where you want the new git repository of readline to live.

**Comment by Ninlives** [comment]
Oh, I see, thank you :P

**Comment by willghatch** [comment]
When I pushed the breaking commit (IE the one requiring the new functionality), the readline package was already updated.  I didn't at the time think about the fact that (I think) the core libraries are pinned for releases, but other packages aren't (or at least they're not without some intervention).  I'm hoping this issue is resolved in the upcoming release, but for future such breaking things I'll try to keep them in a separate branch if they require not-yet-released features.

That said, this feature (and another I'm trying to get into readline right now) really improve interactive rash usage a lot (to the point where with these two features I'm now using rash as my main shell).  But I'm really not *trying* to make it harder to try rash...

**Comment by willghatch** [comment]
Now that the new functionality is in the released version (version 6.12), I am adding the changes back.  So the current version of this package will no longer work on 6.11 or earlier without updating the `readline-lib` package to a newer version.
