### ISSUE TITLE
string colorizer for prompts

### ISSUE THREAD

**Issue by vityou** [willghatch/racket-rash#31]
I noticed you said it would be nice to have a suite of functions to design prompts, so I made a function that can add color (and other things) to a string in the form of ANSI escape sequences.  It supports 4 bit, 8 bit, and 24 bit colors.  It has other common style options like bold and underline.  And you can also add your own commands and it appends them.  Currently no hexadecimal support (only r,g,b form) but that would be easy to add.  Here is the function: https://github.com/vityou/rash-files/blob/master/prompt-helpers/string-color.rkt Let me know if you'd like to use it or if theres anything I could change/add.

**Comment by vityou** [comment]
Just added hex color support.

**Comment by willghatch** [comment]
Looks good.  Some comments:

* You should `(provide create-colored-string)`.
* The require of `rashrc-git-stuff` is unnecessary.
* It's good as it is, but it's often convenient to be able to nest styles within each other and have it come out right.  Do you think it would make sense to have a function that will emit structs that contain style information and a list of strings or sub-styled-string structs, and then have a function that converts them all into a string styled properly by applying `create-colored-string` to each sub-element?  Eg. it could look like `(colored-string-struct->string (colored-string-struct "this is green" (colored-string-struct " this is red but still underlined " #:fg "red") "this is green again" #:fg "green" #:underlined? #t))`.  But perhaps with better names.  And I'm not sure whether it makes more sense to have the middle one be underlined or not.  I would lean to yes, except when the inner one specifies otherwise explicitly.  At any rate, I'm happy to include it in Rash with or without the enhancements -- maybe in `rash/prompt-helpers/string-color.rkt`.  Feel free to submit a PR.
* In addition to numbers and strings, you might accept Racket's `color%` objects.  At least as long as that doesn't pull in any dependencies on GUI stuff.  But I don't really have strong feelings either way.
* I notice that it has Windows line endings.  This combined with your issue about readline not working on Windows leads me to believe you are perhaps primarily a Windows user?  If so, have you found any other problems with Rash besides that?  I've been meaning to add command-line options to, among other things, not use readline.  As far as I know everything else works on Windows -- at least it did several months or a year ago when I tested it once.  But any testing you do on windows would be helpful as well.

**Comment by vityou** [comment]
> You should (provide create-colored-string).
> The require of rashrc-git-stuff is unnecessary.

Yeah the function sort of evolved from me trying to create a powerline prompt and I forgot to clean it up.

> It's good as it is, but it's often convenient to be able to nest styles within each other and have it come out right...

Yeah, structs seem like a good idea here as they can store the string and the style info.  I would assume the `struct->string` function takes care of the nested structs by storing the outer style, making the nested style `(string-append outer inner)` so inner can override, then clearing all the style and re-applying the outer style for the rest of the struct.  If inner structs didn't inherit style from the outer ones, the nesting ability wouldn't do much good.  I guess the struct function could have a `#:reset-before?` like the current function.

I can provide the current function and a struct one if you want, or just the struct one.

I'll check out `color%` as well.

> I notice that it has Windows line endings. This combined with your issue about readline not working on Windows leads me to believe you are perhaps primarily a Windows user? If so, have you found any other problems with Rash besides that?

Unfortunately, I do have windows installed, but mainly for compatibility.  I mainly use arch, but when I'm on windows, I use the wsl to run rash, and I would probably recommend that to anyone interested in both command line interfaces and windows.  I haven't been able to run rash on bare windows due to the readline issue, but I will try to find a windows version of readline so I can do that.

**Comment by vityou** [comment]
I don't think this could opacity, right?  Because `color%` has an alpha value. I'm just gonna ignore it unless there's a special formula that can incorporate opacity into rgb.  I know there is one if you know the background color, but that's part of the terminal, not the shell I believe.  I would have to redesign how fg displays as well, because the fg could have an opacity in relation to the bg.

**Comment by vityou** [comment]
I'll close this now that the pr is submitted.
