### ISSUE TITLE
rash-lang.org

### ISSUE THREAD

**Issue by vityou** [willghatch/racket-rash#41]
I'll just put this up here as a future plan.  I could maybe start making a rudimentary homepage for rash-lang.org, perhaps with pollen or something like that.  GitHub lets you host a static website under a gh-pages branch, I believe.

**Comment by vityou** [comment]
Perhaps something like this:
![rash-plan](https://user-images.githubusercontent.com/10042016/45920952-1a7c5700-be69-11e8-99ac-fddd03cb1b1b.png)

**Comment by willghatch** [comment]
That would be great, I would be very happy if you did that.  I've sort of intended to make a web page at some point, but haven't gotten around to it.  The first thing I would have reached for is some sort of degenerate front-page-only frog blog, but if you have a plan for something with pollen that would be even better.  I've never made a website that people find visually appealing, and your logo has impressed me that you will probably do much better at designing something good.

**Comment by vityou** [comment]
I'm not sure there would be much benefit to using pollen for this as it would mainly be a few main points and links to other places.  Then again, racket-lang.org was made with pollen (I think), and it looks pretty good, however I'm not sure if they just used it because it was pollen.

Maybe I can try a simple index file and see if it needs expanding with some framework like pollen.

**Comment by vityou** [comment]
Ok the base website is complete but a little lacking in terms of content.  So far it looks like:


![capture](https://user-images.githubusercontent.com/10042016/45985828-552aee80-c025-11e8-87ab-e3cbb9fff14d.PNG)

**Comment by vityou** [comment]
I have the code in a gh-pages branch on my fork.  If you want to create a gh-pages branch in this repo I can make a PR.

**Comment by pmatos** [comment]
Looks great already! Very excited about rash.

**Comment by willghatch** [comment]
Thanks, Vityou!  This looks great so far.

I'm somewhat hesitant to use github pages, because I feel like I would rather have the page just sit on the domain rash-lang.org and not have all the eg. links and search engine results pointing to github.io.  Maybe it's silly, but I sort of use github for convenience but have always imagined it likely that I would want to move somewhere else at some point.  For instance, I think some other repo hosting projects will implement federation, and then I would rather be on a free instance of a network using a federated open protocol than on a proprietary code hosting site.  (I'm sure I would still have github as a mirror, and maybe take pull requests from both, but I want to support an open protocol once it becomes practical and have the canonical repo there.)  So I think I might rather just have a website repo that I can host on a server that rash-lang.org points to.

If we do just use github pages, do you guys know a better way to redirect rash-lang.org to the appropriate website than html redirect?  If the github pages URL were just the top-level domain name I might make rash-lang.org a cname in DNS, but it includes a sub-directory in the URL, so I don't think that approach can work.  With the html redirect I've got so far (that is currently just pointing to the github page), it has a bit of delay and my browser temporarily shows a message that it's redirecting.

But I'm fairly well leaning towards just having a stand-alone website at rash-lang.org.  So I think I'll make a new rash-lang.org repository and make your gh-pages branch be the master branch of the website repository.  Then I'll just have the web server clone the website repo.

**Comment by vityou** [comment]
Oh yeah, a stand alone web server sounds fine to me.  Unfortunately, I have next to zero knowledge in the domain of networks and servers and protocols and similar things, so I just suggested gh pages because it's all I really know about.

**Comment by willghatch** [comment]
It's now live at `rash-lang.org`.  I made a couple minor edits (I am fond of the “Reckless Racket Shell” tagline).  Thanks!

**Comment by willghatch** [comment]
Oh, and the repository for it is `https://github.com/willghatch/rash-lang.org`
