### ISSUE TITLE
Error during setup

### ISSUE THREAD

**Issue by pmatos** [willghatch/racket-rash#5]
While trying to setup rash on 6.10.1 with `raco pkg install rash` I get:
```
pre-readline-input-port: unbound identifier in module
```
while compiling `repl.rkt`

**Comment by willghatch** [comment]
Ok, I've fixed it in the main branch.

The problem is that `pre-readline-input-port` is in the git version of the readline-lib package, but until the next Racket release comes out, you can only get it by doing `raco pkg update --clone readline-lib` or by building the pre-release/git versions of racket.

Anyway, I've put all that into a separate branch until the upcoming release, so the install doesn't have any errors.

**Comment by willghatch** [comment]
Just a note -- since the new `readline-lib` features are finally out in the new release, I have merged the commit that re-enables readline.  So the package will now "just work" on Racket 6.12, but will no longer work on 6.11 and earlier without using an updated `readline-lib` package.
