### ISSUE TITLE
Request: rash arguments

### ISSUE THREAD

**Issue by pmatos** [willghatch/racket-rash#8]
In rash, it seems I cannot do `(define foo "ls -l") (rash foo)`. Is there another way of achieving this?

**Comment by willghatch** [comment]
It doesn't work because `foo` is a runtime definition of a string, and the `rash` macro expects, at compile time, a syntax object that contains a string.  So the `"ls -l"` string and the `rash` macro live at two different phases, and what the macro sees is a syntax object with the symbol `foo` inside.

I'm not sure what context you are trying to do this in, but there are various approaches you might take to do things that seem to be related.

If you are just trying to use different commands and arguments computed dynamically, you could use variables in the unix command, like this: `(rash «$command (compute-args)»)` (Note that the arguments will splice if they are a list.  `$args` should support splicing too, but I need to improve the dollar expansion to be more flexible -- right now it converts everything into a string, so you can't splice a list of arguments with it.)

If you want a whole pipeline segment to be computed dynamically (eg. to pass something like `'(ls -l)`), you could make an operator that just accepts the runtime pipeline-member objects.  (This should by all means exist as one of the default available operators, I just haven't made it yet.  I am also planning to add better support for using the DSL to create first-class pipeline segments, but I haven't yet decided what I want to do for certain edge cases.  But it would be a really easy pipeline operator to make yourself if you want to try your hand at making one.)  If you only want this for subprocess pipeline segments, you could also use `(rash «(compute-everything)»)`, although that maybe wouldn't make a lot of sense unless it were part of a larger pipeline. 

If you want to pass a string specifically instead of a list and have it be parsed as a command, eg. `"ls -l"` instead of `'(ls -l)`, it would be easy to give this basic support by just splitting the string and passing it to the operator described above.  But it wouldn't have support for anything fancy like dollar escapes without a little more elbow grease.

I guess for completeness I might say you could use eval, but that's probably a bad idea for most cases.

Does that help?

**Comment by willghatch** [comment]
If you haven't been following Rash, the `rash` macro is no longer the recommended way to escape back into line-mode, but rather just using `{}` braces is recommended.

Should I close this issue, or is there anything else to address?  Thanks.

**Comment by pmatos** [comment]
@willghatch Haven't been following new developments but I gave it a try and it looks good. Thanks. Closing.
